### ISSUE TITLE
Sonarr quality profile import failures

### ISSUE THREAD

**Issue by mwarkentin** [Dictionarry-Hub/profilarr#138]
Version: `2185f72385779789ea72b738d6483479260471fa` from `dev` branch

If this kind of breakage on `dev` is expected just let me know . :) 

Logs:

```
$ python importarr.py
Select your app of choice
1. radarr
2. sonarr
Enter your choice:
2
Select your Sonarr instance
1. Sonarr (Main)
Choose an instance by number, multiple numbers separated by commas or type 'all' for all instances:
1

Importing custom formats to Sonarr : Main

Updating custom format 'D-Z0N3' : SUCCESS
Updating custom format 'DON' : SUCCESS
Updating custom format 'EbP' : SUCCESS
Updating custom format 'Geek' : SUCCESS
Updating custom format 'TayTo' : SUCCESS
Updating custom format 'ZQ' : SUCCESS
Updating custom format 'VietHD' : SUCCESS
Updating custom format 'CtrlHD' : SUCCESS
Updating custom format 'HiFi' : SUCCESS
Updating custom format 'FoRM' : SUCCESS
Updating custom format 'HiDt' : SUCCESS
Updating custom format 'SA89' : SUCCESS
Updating custom format 'CRiSC' : SUCCESS
Updating custom format 'NTb' : SUCCESS
Updating custom format 'decibeL' : SUCCESS
Updating custom format 'NCmt' : SUCCESS
Updating custom format 'de[42]' : SUCCESS
Updating custom format 'IDE' : SUCCESS
Updating custom format 'HDMaNiAcS' : SUCCESS
Updating custom format 'LolHD' : SUCCESS
Updating custom format 'BMF' : SUCCESS
Updating custom format 'EA' : SUCCESS
Updating custom format 'TBB' : SUCCESS
Updating custom format 'nmd' : SUCCESS
Updating custom format 'SbR' : SUCCESS
Updating custom format 'PTer' : SUCCESS
Updating custom format 'Dariush SD' : SUCCESS
Updating custom format 'TDD' : SUCCESS
Updating custom format 'Penumbra' : SUCCESS
Updating custom format 'FTW-HD' : SUCCESS
Updating custom format 'xander' : SUCCESS
Updating custom format 'Chotab' : SUCCESS
Updating custom format 'ESiR' : SUCCESS
Updating custom format 'Positive' : SUCCESS
Updating custom format 'ORiGEN' : SUCCESS
Updating custom format 'SaNcTi' : SUCCESS
Updating custom format 'ThD' : SUCCESS
Updating custom format 'ZIMBO' : SUCCESS
Updating custom format 'NyHD' : SUCCESS
Updating custom format 'luvBB' : SUCCESS
Updating custom format 'GALAXY' : SUCCESS
Updating custom format 'HiP' : SUCCESS
Updating custom format 'GS88' : SUCCESS
Updating custom format 'W4NK3R' : SUCCESS
Updating custom format 'SiMPLE' : SUCCESS
Updating custom format 'BV' : SUCCESS
Updating custom format 'GutS' : SUCCESS
Updating custom format 'E.N.D' : SUCCESS
Updating custom format 'playHD' : SUCCESS
Updating custom format 'WMING' : SUCCESS
Updating custom format 'KASHMiR' : SUCCESS
Updating custom format 'c0ke' : SUCCESS
Updating custom format 'HANDJOB' : SUCCESS
Updating custom format 'EDPH' : SUCCESS
Updating custom format 'MTeam' : SUCCESS
Updating custom format 'iFT' : SUCCESS
Updating custom format 'FraMeSToR' : SUCCESS
Updating custom format 'LEGi0N' : SUCCESS
Updating custom format 'BHDStudio' : SUCCESS
Updating custom format '1080p' : SUCCESS
Updating custom format '720p' : SUCCESS
Updating custom format '2160p' : SUCCESS
Updating custom format 'Blu-Ray' : SUCCESS
Updating custom format 'WEBRip' : SUCCESS
Updating custom format 'x264' : SUCCESS
Updating custom format 'REMUX' : SUCCESS
Updating custom format 'Amazon Prime' : SUCCESS
Updating custom format 'Movies Anywhere' : SUCCESS
Updating custom format 'Apple TV+' : SUCCESS
Updating custom format 'Disney+' : SUCCESS
Updating custom format 'HBO Max' : SUCCESS
Updating custom format 'Netflix' : SUCCESS
Updating custom format 'Hulu' : SUCCESS
Updating custom format 'Peacock TV' : SUCCESS
Updating custom format 'Paramount+' : SUCCESS
Updating custom format 'iTunes' : SUCCESS
Updating custom format 'DD+' : SUCCESS
Updating custom format 'DTS' : SUCCESS
Updating custom format 'DD' : SUCCESS
Updating custom format 'ATMOS' : SUCCESS
Updating custom format 'IMAX' : SUCCESS
Updating custom format 'x265' : SUCCESS
Updating custom format 'DTS-HD MA' : SUCCESS
Updating custom format 'FLAC' : SUCCESS
Updating custom format 'DTS-X' : SUCCESS
Updating custom format 'TrueHD' : SUCCESS
Updating custom format 'Black and White' : SUCCESS
Updating custom format 'RightSIZE' : SUCCESS
Updating custom format 'Unwanted' : SUCCESS
Updating custom format '3D' : SUCCESS
Updating custom format 'Disc ' : SUCCESS
Updating custom format 'BeyondHD' : SUCCESS
Updating custom format 'ROKU' : SUCCESS
Updating custom format 'iTunes (Missing)' : SUCCESS
Updating custom format 'HANDJOB SD' : SUCCESS
Updating custom format 'DVD REMUX ' : SUCCESS
Updating custom format 'DVD' : SUCCESS
Updating custom format 'Xvid' : SUCCESS
Updating custom format 'TBB SD' : SUCCESS
Updating custom format 'Dariush ' : SUCCESS
Updating custom format '480p' : SUCCESS
Updating custom format 'Extras' : SUCCESS
Updating custom format 'VVC' : SUCCESS
Updating custom format 'AV1' : SUCCESS
Updating custom format 'mHD' : SUCCESS
Updating custom format 'Scene' : SUCCESS
Updating custom format 'LoRD' : SUCCESS
Updating custom format 'Stream Optimised' : SUCCESS
Updating custom format 'HDR10+' : SUCCESS
Updating custom format 'Dolby Vision' : SUCCESS
Updating custom format 'HDR10' : SUCCESS
Updating custom format 'HDR10 (Missing)' : SUCCESS
Updating custom format 'TrueHD (Missing)' : SUCCESS
Updating custom format 'ATMOS (Missing)' : SUCCESS
Updating custom format 'UHDBits' : SUCCESS
Updating custom format 'Dolby Vision w/out Fallback' : SUCCESS
Updating custom format '3L' : SUCCESS
Updating custom format 'TRiToN' : SUCCESS
Updating custom format 'WiLDCAT' : SUCCESS
Updating custom format 'PmP' : SUCCESS
Updating custom format 'BLURANiUM' : SUCCESS
Updating custom format 'playBD' : SUCCESS
Updating custom format 'EPSiLON' : SUCCESS
Updating custom format 'LQ' : SUCCESS
Updating custom format 'CJ' : SUCCESS
Updating custom format 'pcroland' : SUCCESS
Updating custom format 'BTN' : SUCCESS
Updating custom format 'iON' : SUCCESS
Updating custom format 'AJP69' : SUCCESS
Updating custom format 'VLAD' : SUCCESS
Updating custom format 'hdalx' : SUCCESS
Updating custom format 'LiNG' : SUCCESS
Updating custom format 'h265' : SUCCESS
Updating custom format 'Blu-Ray (Remux)' : SUCCESS
Updating custom format 'PCM' : SUCCESS
Updating custom format 'h265 (4k)' : SUCCESS
Updating custom format 'MAX' : SUCCESS
Updating custom format 'HR' : SUCCESS
Updating custom format 'x265 (Missing)' : SUCCESS
Updating custom format 'x265 (Web)' : SUCCESS
Updating custom format 'HONE' : SUCCESS
Updating custom format 'NAN0' : SUCCESS
Updating custom format 'LSt' : SUCCESS
Updating custom format 'TimeDistortion' : SUCCESS
Updating custom format 'Chivaman' : SUCCESS
Updating custom format 'MainFrame' : SUCCESS
Updating custom format 'GRiMM' : SUCCESS
Updating custom format 'TAoE' : SUCCESS
Updating custom format 'Vyndros' : SUCCESS
Updating custom format 'Ralphy' : SUCCESS
Updating custom format 'dkore' : SUCCESS
Updating custom format 'edge2020' : SUCCESS
Updating custom format 'AnoZu' : SUCCESS
Updating custom format 'SEV' : SUCCESS
Updating custom format 'LEGi0N (x265)' : SUCCESS
Updating custom format 'R1GY3B / B3YG1R' : SUCCESS
Updating custom format 'QxR' : SUCCESS
Updating custom format 'Upscaled' : SUCCESS

Successfully added 0 custom formats, updated 158 custom formats.

Available profiles:
1. 1080p Balanced (sonarr - master).json
2. 1080p Optimal (sonarr - master).json
3. 1080p Transparent (Double Grab) (sonarr - master).json
4. 1080p Transparent (sonarr - master).json
5. 2160p Optimal (sonarr - master).json
6. Balanced (HEVC) (sonarr - master).json

Enter the numbers of the profiles you want to import separated by commas, or type 'all' to import all profiles:
1,4,6
Importing Quality Profiles to sonarr : Main

HTTP Error 500.
Adding '1080p Balanced' quality profile : FAIL
HTTP Error 500.
Adding '1080p Transparent' quality profile : FAIL
HTTP Error 500.
Adding 'Balanced (HEVC)' quality profile : FAIL
```

**Comment by santiagosayshey** [comment]
Hi, this is probably related to: #137. 

Since you're on the latest Profilarr dev branch, I'm guessing this might be because your Sonarr is not up to date with stable. Could you paste your sonarr error logs please?

**Comment by mwarkentin** [comment]
Here you go:

```
[v4.0.9.2244] System.ArgumentException: ID does not match a known quality (Parameter 'id')
   at NzbDrone.Core.Qualities.Quality.FindById(Int32 id) in ./Sonarr.Core/Qualities/Quality.cs:line 191
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileQualityItemResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 117
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 97
   at Sonarr.Api.V3.Profiles.Quality.QualityProfileController.Create(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileController.cs:line 51
   at lambda_method676(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-11-03 19:13:58.2|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/qualityprofile

[v4.0.9.2244] System.ArgumentException: ID does not match a known quality (Parameter 'id')
   at NzbDrone.Core.Qualities.Quality.FindById(Int32 id) in ./Sonarr.Core/Qualities/Quality.cs:line 191
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileQualityItemResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 117
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 97
   at Sonarr.Api.V3.Profiles.Quality.QualityProfileController.Create(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileController.cs:line 51
   at lambda_method676(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-11-03 19:13:58.3|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/qualityprofile

[v4.0.9.2244] System.ArgumentException: ID does not match a known quality (Parameter 'id')
   at NzbDrone.Core.Qualities.Quality.FindById(Int32 id) in ./Sonarr.Core/Qualities/Quality.cs:line 191
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileQualityItemResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 117
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Sonarr.Api.V3.Profiles.Quality.ProfileResourceMapper.ToModel(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileResource.cs:line 97
   at Sonarr.Api.V3.Profiles.Quality.QualityProfileController.Create(QualityProfileResource resource) in ./Sonarr.Api.V3/Profiles/Quality/QualityProfileController.cs:line 51
   at lambda_method676(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by santiagosayshey** [comment]
ah yep. You'll need to update sonarr to `4.0.10.2544`. It's a hard [requirement](https://github.com/Dictionarry-Hub/profilarr?tab=readme-ov-file#prerequisites) to be on the latest version now so that we don't have to maintain different versions of quality profiles. 

That should fix everything up, just let me know if it's still not working. Sorry for the inconvenience!

**Comment by mwarkentin** [comment]
@santiagosayshey would it make sense to handle that error and provide some guidance inline? Something like:

```
HTTP Error 500.
Adding '1080p Balanced' quality profile : FAIL
Make sure you've installed the most recent stable build of sonarr to ensure compatibility.
```

**Comment by santiagosayshey** [comment]
@mwarkentin yeah totally, I'll add this to the todo list! Thanks for the suggestion

https://discord.com/channels/1202375791556431892/1303109595933311026

**Comment by mwarkentin** [comment]
Just confirming this worked after I updated sonarr to latest :)

```
Enter the numbers of the profiles you want to import separated by commas, or type 'all' to import all profiles:
1,4,6
Importing Quality Profiles to sonarr : Main

Adding '1080p Balanced' quality profile : SUCCESS
Adding '1080p Transparent' quality profile : SUCCESS
Adding 'Balanced (HEVC)' quality profile : SUCCESS
```
